local excluded = { 
    -- binary assets
    "*.uasset",
    "*.umap",
    "*.fbx",
    "*.png",
    "*.wav",
    "*.ttf" ,
    -- generated by Unreal and Clangd
    "Intermediate/",
    "Saved/",
    "Binaries/",
    "DerivedDataCache/",
    "Content/",
    "compile_commands.json",
}
local exclude_globs = {}
for _, pattern in ipairs(excluded) do
    table.insert(exclude_globs, "--glob=!" .. pattern)
end

return {
	"nvim-telescope/telescope.nvim",
	version = "*",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope-ui-select.nvim",
	},
	opts = function(_, opts)
		-- set default picker theme to ivy for all pickers
		local actions = require("telescope.actions")
		opts.defaults = require("telescope.themes").get_ivy({
			layout_config = { height = 0.30 },
			mappings = {
				i = {
					["<M-j>"] = actions.move_selection_next,
					["<M-k>"] = actions.move_selection_previous,
				},
				n = {
					["<M-j>"] = actions.move_selection_next,
					["<M-k>"] = actions.move_selection_previous,
				},
			},
		})
        opts.picker = {
            find_files = {
                find_command = vim.list_extend({
                    "rg",
                    "--files",
                    "--color=never"
                }, vim.deepcopy(exclude_globs)),
            },
            live_grep = {
                additional_args = function()
                    return exclude_globs
                end
            }
        }
	end,
	config = function(_, opts)
		require("telescope").setup(opts)

		local builtin = require("telescope.builtin")
		vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
		vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Telescope live grep" })
		vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
		vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })
	end,
}
